// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP9ZVpC6KT-R80dL5-c9Cz4h8aXqyMAvY',
    appId: '1:195986368975:web:2460dc3bbd90b4e8254aba',
    messagingSenderId: '195986368975',
    projectId: 'homework-04-messageboardapp',
    authDomain: 'homework-04-messageboardapp.firebaseapp.com',
    storageBucket: 'homework-04-messageboardapp.firebasestorage.app',
    measurementId: 'G-D7179QKBJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8P3FsCYIvCqM_NUtoPeheiQwD5QWBA1E',
    appId: '1:195986368975:android:7603952226d0edab254aba',
    messagingSenderId: '195986368975',
    projectId: 'homework-04-messageboardapp',
    storageBucket: 'homework-04-messageboardapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwtygIl8mn-jLy9xqiPjbQPfDV_KlHkqI',
    appId: '1:195986368975:ios:a9a735497b7d7d5f254aba',
    messagingSenderId: '195986368975',
    projectId: 'homework-04-messageboardapp',
    storageBucket: 'homework-04-messageboardapp.firebasestorage.app',
    iosBundleId: 'com.example.homework04MessageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwtygIl8mn-jLy9xqiPjbQPfDV_KlHkqI',
    appId: '1:195986368975:ios:a9a735497b7d7d5f254aba',
    messagingSenderId: '195986368975',
    projectId: 'homework-04-messageboardapp',
    storageBucket: 'homework-04-messageboardapp.firebasestorage.app',
    iosBundleId: 'com.example.homework04MessageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP9ZVpC6KT-R80dL5-c9Cz4h8aXqyMAvY',
    appId: '1:195986368975:web:cf23dd68b8c69b38254aba',
    messagingSenderId: '195986368975',
    projectId: 'homework-04-messageboardapp',
    authDomain: 'homework-04-messageboardapp.firebaseapp.com',
    storageBucket: 'homework-04-messageboardapp.firebasestorage.app',
    measurementId: 'G-H1T3CX8HMZ',
  );
}
